In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow.keras as kera
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout, Input, Flatten
from tensorflow.keras.losses import BinaryCrossentropy, CategoricalCrossentropy, SparseCategoricalCrossentropy, MeanSquaredError
from tensorflow.keras.optimizers import Adam, SGD, RMSprop
from tensorflow.keras.activations import linear, relu

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from numpy import sqrt

from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
train_df = pd.read_csv('./data/train.csv')
test_df = pd.read_csv('./data/test.csv')

In [3]:
train_df.head(10)

,id,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_122,col_123,col_124,col_125,col_126,col_127,col_128,col_129,col_130,target
0,2,A,B,A,A,A,A,A,A,B,...,0.438917,0.436585,0.60087,0.35127,0.43919,0.338312,0.366307,0.611431,0.304496,1283.60
1,5,A,B,A,A,B,A,A,A,B,...,0.289648,0.315545,0.27320,0.26076,0.32446,0.381398,0.373424,0.195709,0.774425,3005.09
2,10,B,B,A,B,A,A,A,A,B,...,0.440945,0.391128,0.31796,0.32128,0.44467,0.327915,0.321570,0.605077,0.602642,939.85
3,11,A,B,A,B,A,A,A,A,B,...,0.178193,0.247408,0.24564,0.22089,0.21230,0.204687,0.202213,0.246011,0.432606,2763.85
4,13,A,B,A,A,A,A,A,A,B,...,0.364464,0.401162,0.26847,0.46226,0.50556,0.366788,0.359249,0.345247,0.726792,5142.87
5,14,A,A,A,A,B,A,A,A,A,...,0.381515,0.363768,0.24564,0.40455,0.47225,0.334828,0.352251,0.342239,0.382931,1132.22
6,20,A,B,A,B,A,A,A,A,B,...,0.867021,0.583389,0.90267,0.84847,0.80218,0.644013,0.785706,0.859764,0.242416,3585.75
7,23,A,B,B,B,B,A,A,A,B,...,0.628534,0.384099,0.61229,0.38249,0.51111,0.682315,0.669033,0.756454,0.361191,10280.20
8,24,A,B,A,A,B,B,A,A,B,...,0.713343,0.469223,0.30260,0.67135,0.83510,0.863052,0.879347,0.822493,0.294523,6184.59
9,33,A,B,A,A,B,A,A,A,B,...,0.314683,0.370419,0.58354,0.46226,0.38016,0.644013,0.665644,0.339244,0.799124,5965.73

In [4]:
train_df.tail(10)

,id,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_122,col_123,col_124,col_125,col_126,col_127,col_128,col_129,col_130,target
169476,587605,B,A,A,A,A,B,A,A,A,...,0.599275,0.548122,0.48864,0.45391,0.64056,0.592525,0.590961,0.701266,0.362479,1173.30
169477,587606,A,A,A,A,B,A,A,A,A,...,0.201125,0.259395,0.24564,0.30859,0.21983,0.207238,0.204687,0.357400,0.348217,2161.12
169478,587607,A,B,A,B,B,B,A,A,B,...,0.269520,0.338963,0.33906,0.28066,0.30529,0.245410,0.261799,0.181433,0.398571,4080.42
169479,587612,A,A,A,A,B,A,A,A,A,...,0.502705,0.473897,0.43518,0.66201,0.58257,0.415029,0.406090,0.354344,0.377315,994.85
169480,587619,A,A,A,A,A,B,A,A,A,...,0.445008,0.377930,0.36636,0.29095,0.44467,0.327915,0.321570,0.731059,0.721499,804.28
169481,587620,A,B,A,A,A,A,A,A,B,...,0.242437,0.289949,0.24564,0.30859,0.32935,0.223038,0.220003,0.333292,0.208216,1198.62
169482,587624,A,A,A,A,A,B,A,A,A,...,0.334270,0.382000,0.63475,0.40455,0.47779,0.307628,0.301921,0.318646,0.305872,1108.34
169483,587630,A,B,A,A,A,A,A,B,B,...,0.345883,0.370534,0.24564,0.45808,0.47779,0.445614,0.443374,0.339244,0.503888,5762.64
169484,587632,A,B,A,A,A,A,A,A,B,...,0.704364,0.562866,0.34987,0.44767,0.53881,0.863052,0.852865,0.654753,0.721707,1562.87
169485,587633,B,A,A,B,A,A,A,A,A,...,0.844563,0.533048,0.97123,0.93383,0.83814,0.932195,0.946432,0.810511,0.721460,4751.72

In [5]:
%%time
cat = [f'col_{i}' for i in range(1, 117)]
con = [f'col_{i}' for i in range(117, 131)]
for c in cat:
    train_df[c] = train_df[c].astype('category')
    test_df[c] = test_df[c].astype('category')
    train_df[c] = train_df[c].cat.codes
    test_df[c] = test_df[c].cat.codes
del c
train_df.drop('id', axis=1, inplace=True)
test_df.drop('id', axis=1, inplace=True)

Wall time: 12.4 s

In [6]:
train_df.columns

Index(['col_1', 'col_2', 'col_3', 'col_4', 'col_5', 'col_6', 'col_7', 'col_8',
       'col_9', 'col_10',
       ...
       'col_122', 'col_123', 'col_124', 'col_125', 'col_126', 'col_127',
       'col_128', 'col_129', 'col_130', 'target'],
      dtype='object', length=131)

In [7]:
X = train_df.iloc[:,train_df.columns != 'target'].values
y = train_df.iloc[:,train_df.columns == 'target'].values

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train)
del X, y

In [9]:
X_train.shape

(95335, 130)

In [10]:
activation_fn = 'relu'
model = Sequential()
model.add(Input(shape=(130,)))
model.add(Dense(260, activation=activation_fn))
model.add(Dense(130, activation=activation_fn))
model.add(Dense(65, activation=activation_fn))
model.add(Dense(1, activation=linear))
model.compile(optimizer=RMSprop(learning_rate=1e-3), loss=MeanSquaredError(), metrics=['mse', 'mae'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 260)               34060
_________________________________________________________________
dense_1 (Dense)              (None, 130)               33930
_________________________________________________________________
dense_2 (Dense)              (None, 65)                8515
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 66
=================================================================
Total params: 76,571
Trainable params: 76,571
Non-trainable params: 0
_________________________________________________________________

In [11]:
mse_history = []
mae_history = []

In [ ]:
%%time
init_epochs = 0
epochs_now = 100
history = model.fit(X_train, y_train, epochs=epochs_now, validation_data=(X_val, y_val), initial_epoch=init_epochs)
mse_history += history.history['mse']
mae_history += history.history['mae']
model.save(f'linear_4/model_{epochs_now}.h5')

Epoch 1/100
2980/2980 [==============================] - 13s 4ms/step - loss: 5424851.5000 - mse: 5424851.5000 - mae: 1459.7018 - val_loss: 5032704.5000 - val_mse: 5032704.5000 - val_mae: 1697.2418
Epoch 2/100
2980/2980 [==============================] - 14s 5ms/step - loss: 4593660.0000 - mse: 4593660.0000 - mae: 1334.7026 - val_loss: 4005077.2500 - val_mse: 4005077.2500 - val_mae: 1316.4584
Epoch 3/100
2980/2980 [==============================] - 12s 4ms/step - loss: 4507337.0000 - mse: 4507337.0000 - mae: 1317.4562 - val_loss: 3945072.7500 - val_mse: 3945072.7500 - val_mae: 1260.7466
Epoch 4/100
 744/2980 [======>.......................] - ETA: 5s - loss: 4690207.5000 - mse: 4690207.5000 - mae: 1314.5917

In [ ]:
%%time
init_epochs = 100
epochs_now = 500
history = model.fit(X_train, y_train, epochs=epochs_now, validation_data=(X_val, y_val), initial_epoch=init_epochs)
mse_history += history.history['mse']
mae_history += history.history['mae']
model.save(f'linear_4/model_{epochs_now}.h5')

In [ ]:
%%time
init_epochs = 500
epochs_now = 1000
history = model.fit(X_train, y_train, epochs=epochs_now, validation_data=(X_val, y_val), initial_epoch=init_epochs)
mse_history += history.history['mse']
mae_history += history.history['mae']
model.save(f'linear_4/model_{epochs_now}.h5')

In [ ]:
%%time
init_epochs = 1000
epochs_now = 5000
history = model.fit(X_train, y_train, epochs=epochs_now, validation_data=(X_val, y_val), initial_epoch=init_epochs)
mse_history += history.history['mse']
mae_history += history.history['mae']
model.save(f'linear_4/model_{epochs_now}.h5')

In [ ]:
plt.plot(mae_history)
plt.show()
plt.plot(mse_history)
plt.show()